<template>
  <button
    class="bottom-right-button"
    @click="$emit('toggleVisible', 'visible')"
  >
    <Icon
      icon="entypo:plus"
      style="width: 24px; height: 24px"
      class="plus-icon"
    />
  </button>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Icon } from "@iconify/vue";
export default defineComponent({
  data() {
    return {
      visible: false,
    };
  },
  methods: {
    toggleVisible() {
      alert();
      this.visible = !this.visible;
    },
  },
  emits: ["toggleVisible"],
  components: {
    Icon,
  },
});
</script>

<style>
.bottom-right-button {
  position: absolute;
  right: 5%;
  bottom: 20%;
  z-index: 999;

  padding: 10px;

  border: 1px solid #222832;
  border-radius: 50%;
  background: #222831;
  color: #eee;
}

.bottom-right-button:hover {
  border: 1px solid #fd7014;
  background: #fd7014;
  transition: 250ms ease-in;
  box-shadow: 0px 0px 20px 0px rgba(253, 112, 20, 0.75);
}

.plus-icon:hover {
  animation: heartbeat 1.5s ease-in-out infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-4-8 17:40:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(2);
    transform: scale(2);
    -webkit-transform-origin: center center;
    transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
    transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
    transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
    transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(2);
    transform: scale(2);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(2);
    transform: scale(2);
    -webkit-transform-origin: center center;
    transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
    transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
    transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
    transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(2);
    transform: scale(2);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}

@media screen and (min-width: 732px) and (max-width: 1208px) {
  .bottom-right-button {
    background: #393e46;
  }
}
</style>
